# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb38edf246bed82f5b878876464a4c99232ea8f4389c670f65b03ceeb35a6124bc74befdf10fe9ba5b125a6d796cf08200de421b3b346b2d1eafa553c06d1e03
  stripe_publishable_key: pk_test_7Xrz5QNBAV1vJCf3hRMBEtKS
  stripe_secret_key: sk_test_vGMPaW1vKvvvu5KFZzazu4rQ
  stripe_client_id: ca_7wEEv2y9YWFVZUXXS4fpfA5kouAhfQme

test:
  secret_key_base: 2f0c81d3cbafb6d48faf7201e512be922ad20ec7e1b40bc0a0b89106a8d76b7b5131cda4b679c164f9ced93be59957662d66ba029c3c5c4e7977f6047a19015a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 2f0c81d3cbafb6d48faf7201e512be922ad20ec7e1b40bc0a0b89106a8d76b7b5131cda4b679c164f9ced93be59957662d66ba029c3c5c4e7977f6047a19015a
  stripe_publishable_key: pk_live_8uedVKrNzB1l42zLYdI0Tu8u
  stripe_secret_key: sk_live_RKNcLNAaDbBX8iy4URtl5red
  stripe_client_id: ca_7wEEsp1uhTzliF5GdCZWgTribw5xjTFT
